# You will need this extension below to make it work.
# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.0
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:5000/tutorials

###

GET https://example.com/topics/1

###

POST https://example.com/comments
content-type: application/json

{
    "title": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}