# You will need this extension below to make it work.
# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.0
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:5000/tutorials

###

GET https://example.com/topics/1

###

POST http://localhost:5000/tutorials
content-type: application/json

{
    {
    "title": "sample",
    "instructions": "This is our instructions",
    "ability": "beginner",
    "creator": "joe",
    "materials": ["wood", "string"],
    "videoUrl": "http something",
    "imageUrl": "http something",
    "likes": ["user 1"],
    "comments": ["comment1"],
    "favourites": ["favourite1"]
    }
}
