# You will need this extension below to make it work.
# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.0
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:5000/tutorials


###

GET http://localhost:5000/tutorials/62ebc582c43ca80407


###
DELETE http://localhost:5000/tutorials/62ebcbb85eec6cb5336a34


###

POST http://localhost:5000/tutorials
content-type: application/json

{
    {
    "title": "sample",
    "instructions": "This is our instructions",
    "ability": "beginner",
    "creator": "joe",
    "materials": ["wood", "string"],
    "videoUrl": "http something",
    "imageUrl": "http something",
    "likes": ["user 1"],
    "comments": ["comment1"],
    "favourites": ["favourite1"]
    }
}

###
PATCH http://localhost:5000/tutorials/62ecd7384e7aa5b700a0500f/likeTutorial
content-type: application/json

{
    "userId" : "tass"
}
